### ISSUE TITLE
The levitate/react-export-default rule does not recognize components enclosed in React.forwardRef

### ISSUE THREAD

**Issue by ghost** [ThisIsManta/eslint-plugin-levitate#4]
## Problem

The `levitate/react-export-default` rule does not recognize components enclosed in `React.forwardRef`

![Screen Shot 2021-01-27 at 10 57 17](https://user-images.githubusercontent.com/25390283/105946220-c26c4580-605e-11eb-99b1-333c547936c0.png)

## Environment

- eslint: `7.14.0`
- eslint-plugin-levitate: `3.8.6`
- VSCodium: `1.50.1`
- dbaeumer.vscode-eslint: `2.1.13`

**Comment by ThisIsManta** [comment]
Fixed at v3.15.0 🎉
